wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1694923026.322824
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.15.4
      8:
      - 2
      - 5
algorithm:
  desc: null
  value: ct3
project_name:
  desc: null
  value: epsilon-tester
epsilon:
  desc: null
  value: 0.1
size:
  desc: null
  value: 1000
wandb_key:
  desc: null
  value: c9039a6663b7aa3fa1260f5c004c21cce2584bd1
repeat:
  desc: null
  value: 50
q:
  desc: null
  value:
  - 0.001
  - 0.002
  - 0.003
  - 0.004
  - 0.005
  - 0.006
  - 0.007
  - 0.008
  - 0.009
  - 0.01
