wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702110892.294369
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.7.16
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
algorithm:
  desc: null
  value: adpseq
log_dir:
  desc: null
  value: logs/
data_dir:
  desc: null
  value: data/corel_60.txt
project_name:
  desc: null
  value: assignment-2-debug
application:
  desc: null
  value: setcover
epsilon:
  desc: null
  value:
  - 0.3
mono:
  desc: null
  value: 0.0
unif_cost:
  desc: null
  value: false
car_cons:
  desc: null
  value: 10
wandb_key:
  desc: null
  value: c9039a6663b7aa3fa1260f5c004c21cce2584bd1
