wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1694941596.197731
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.15.4
      8:
      - 2
      - 5
project_name:
  desc: null
  value: epsilon-tester
epsilon:
  desc: null
  value: 0.1
size:
  desc: null
  value: 1000
repeat:
  desc: null
  value: 50
q:
  desc: null
  value:
  - 0.0005
  - 0.001
  - 0.0015
  - 0.002
  - 0.0025
  - 0.003
  - 0.0035
  - 0.004
  - 0.0045
  - 0.005
  - 0.0055
  - 0.006
wandb_key:
  desc: null
  value: c9039a6663b7aa3fa1260f5c004c21cce2584bd1
